In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

In [2]:
data = pd.read_csv('DataBreaches(2004-2021).csv')

In [3]:
data

,Entity,Year,Records,Organization type,Method
0,21st Century Oncology,2016,2200000,healthcare,hacked
1,500px,2020,14870304,social networking,hacked
2,Accendo Insurance Co.,2020,175350,healthcare,poor security
3,Adobe Systems Incorporated,2013,152000000,tech,hacked
4,Adobe Inc.,2019,7500000,tech,poor security
...,...,...,...,...,...
290,Zynga,2019,173000000,social network,hacked
291,Westpac,2019,98000,financial,hacked
292,Unknown agency(believed to be tied to United S...,2020,200000000,financial,accidentally published
293,National Health Information Center (NCZI) of S...,2020,391250,healthcare,poor security
294,Les Éditions Protégez-vous,2020,380000,publisher (magazine),unknown

In [4]:
data['Organization type'].nunique()

54

In [5]:
data['Year'].nunique()

20

In [6]:
data.dtypes

Entity               object
Year                 object
Records               int64
Organization type    object
Method               object
dtype: object

In [7]:
data.describe()

            Records
count  2.950000e+02
mean   4.468863e+07
std    1.959801e+08
min    6.700000e+03
25%    3.075000e+05
50%    2.000000e+06
75%    2.000000e+07
max    3.000000e+09

In [8]:
data['Method'].value_counts()

hacked                                                  156
poor security                                            36
lost / stolen media                                      32
inside job                                               18
accidentally published                                   17
lost / stolen computer                                   15
unknown                                                   4
improper setting, hacked                                  2
poor security/inside job                                  2
intentionally lost                                        1
accidentally exposed                                      1
publicly accessible Amazon Web Services (AWS) server      1
rogue contractor                                          1
misconfiguration/poor security                            1
Poor security                                             1
data exposed by misconfiguration                          1
unprotected api                                           1
poor security / hacked                                    1
accidentally uploaded                                     1
unsecured S3 bucket                                       1
inside job, hacked                                        1
social engineering                                        1
Name: Method, dtype: int64

In [9]:
data['Organization type'].value_counts()

web                                                                         49
healthcare                                                                  45
financial                                                                   36
government                                                                  27
retail                                                                      20
tech                                                                        14
telecoms                                                                    12
academic                                                                    12
gaming                                                                      10
social network                                                               8
military                                                                     6
transport                                                                    5
energy                                                                       3
hotel                                                                        3
social media                                                                 2
government, healthcare                                                       2
media                                                                        2
tech, retail                                                                 2
telecommunications                                                           2
phone accessories                                                            1
government, database                                                         1
web, tech                                                                    1
web, gaming                                                                  1
market analysis                                                              1
Consumer Goods                                                               1
ticket distribution                                                          1
telecom                                                                      1
military, healthcare                                                         1
Telephone directory                                                          1
Clinical Laboratory                                                          1
government, military                                                         1
online marketing                                                             1
mobile carrier                                                               1
tech, web                                                                    1
Question & Answer                                                            1
local search                                                                 1
fashion                                                                      1
QR code payment                                                              1
advertising                                                                  1
educational services                                                         1
banking                                                                      1
game                                                                         1
background check                                                             1
restaurant                                                                   1
financial, credit reporting                                                  1
data broker                                                                  1
financial service company                                                    1
personal and demographic data about residents and their properties of US     1
special public corporation                                                   1
shopping                                                                     1
social networking                                                            1
web, military                                                                1
genealogy                                                                    1
publisher (magazine)                                                         1
Name: Organization type, dtype: int64

In [10]:
data[data['Organization type']=='web']

,Entity,Year,Records,Organization type,Method
11,Ancestry.com,2021,300000,web,poor security
15,AOL,2021,92000000,web,"inside job, hacked"
16,AOL,2021,20000000,web,accidentally published
17,AOL,2014,2400000,web,hacked
21,Ashley Madison,2015,32000000,web,hacked
24,Auction.co.kr,2008,18000000,web,hacked
33,Betfair,2010,2300000,web,hacked
41,Canva,2019,140000000,web,hacked
51,China Software Developer Network,2011,6000000,web,hacked
52,"Chinese gaming websites (three: Duowan, 7K7K, ...",2011,10000000,web,hacked
70,Domino's Pizza (France),2014,600000,web,hacked
71,DoorDash,2019,4900000,web,hacked
73,Dropbox,2012,68648009,web,hacked
74,Drupal,2013,1000000,web,hacked
77,eBay,2014,145000000,web,hacked
86,Evernote,2013,50000000,web,hacked
100,Friend Finder Networks,2016,412214295,web,poor security / hacked
101,Funimation,2016,2500000,web,hacked
102,Formspring,2012,420000,web,accidentally published
104,Gamigo,2012,8000000,web,hacked
106,Gawker,2010,1500000,web,hacked
108,Gmail,2014,5000000,web,hacked
135,KM.RU,2016,1500000,web,hacked
142,"LinkedIn, eHarmony, Last.fm",2012,8000000,web,accidentally published
143,Living Social,2013,50000000,web,hacked
144,MacRumors.com,2014,860000,web,hacked
161,Monster.com,2007,1600000,web,hacked
163,Mozilla,2014,76000,web,poor security
171,Nexon Korea Corp,2011,13200000,web,hacked
182,Orbitz,2018,880000,web,hacked
183,Patreon,2015,2300000,web,hacked
190,Rakuten,2020,1381735,web,"improper setting, hacked"
191,Rambler.ru,2012,98167935,web,hacked
198,Scribd,2013,500000,web,hacked
207,Sony Pictures,2011,1000000,web,hacked
217,Steam,2011,35000000,web,hacked
223,Taringa!,2017,28722877,web,hacked
225,TaxSlayer.com,2016,8800,web,hacked
232,Tianya Club,2011,28000000,web,hacked
240,Tumblr,2013,65469298,web,hacked
241,Twitter,2013,250000,web,hacked
278,Wattpad,2020,270000000,web,hacked
280,Weebly,2016,43430316,web,hacked
281,Writerspace.com,2011,62000,web,hacked
282,Xat.com,2015,6054459,web,social engineering
283,Yahoo,2013,3000000000,web,hacked
284,Yahoo,2014,500000000,web,hacked
286,Yahoo! Voices,2012,450000,web,hacked
289,Zappos,2012,24000000,web,hacked

In [11]:
data[data['Organization type']=='social media']

      Entity  Year   Records Organization type         Method
233   TikTok  2020  42000000      social media  poor security
288  YouTube  2020   4000000      social media  poor security

In [12]:
data[data['Organization type']=='social network']

          Entity  Year    Records Organization type                  Method
90      Facebook  2013    6000000    social network  accidentally published
91      Facebook  2018   50000000    social network           poor security
92      Facebook  2019  540000000    social network           poor security
93      Facebook  2019    1500000    social network   accidentally uploaded
94      Facebook  2019  267000000    social network           poor security
109  Google Plus  2018     500000    social network           poor security
123    Instagram  2020  200000000    social network           poor security
290        Zynga  2019  173000000    social network                  hacked

In [13]:
data['Entity'].value_counts()

Facebook                                5
AOL                                     3
Citigroup                               3
Yahoo                                   2
TD Ameritrade                           2
                                       ..
GS Caltex                               1
Hannaford Brothers Supermarket Chain    1
HauteLook                               1
Health Net                              1
Les Éditions Protégez-vous              1
Name: Entity, Length: 277, dtype: int64

In [14]:
data['Year'].value_counts()

2011             33
2013             26
2019             26
2020             24
2012             22
2018             21
2010             19
2014             18
2015             18
2016             17
2008             16
2009             13
2007             12
2021              9
2005              6
2017              6
2006              6
2018-2019         1
2014 and 2015     1
2004              1
Name: Year, dtype: int64

In [15]:
data[data['Year']=='2011']['Method'].value_counts()

hacked                    17
lost / stolen media        5
lost / stolen computer     4
accidentally published     4
poor security              2
inside job                 1
Name: Method, dtype: int64

In [16]:
data[data['Year']=='2011']['Organization type'].value_counts()

healthcare              8
web                     7
gaming                  4
government              4
financial               3
retail                  2
military                2
military, healthcare    1
academic                1
media                   1
Name: Organization type, dtype: int64

In [17]:
data[data['Organization type'] == 'healthcare']['Method'].value_counts()

hacked                      17
lost / stolen media         14
lost / stolen computer       6
poor security                5
inside job                   2
poor security/inside job     1
Name: Method, dtype: int64

In [18]:
data[data['Organization type']=='gaming']

                          Entity  Year   Records Organization type  Method
12                    Animal Jam  2020  46000000            gaming  hacked
34         Bethesda Game Studios  2011    200000            gaming  hacked
35             Blank Media Games  2018   7633234            gaming  hacked
36        Blizzard Entertainment  2012  14000000            gaming  hacked
173     Nintendo (Club Nintendo)  2013    240000            gaming  hacked
174  Nintendo (Nintendo Account)  2020    160000            gaming  hacked
176               Nival Networks  2016   1500000            gaming  hacked
200                         Sega  2011   1290755            gaming  hacked
206    Sony Online Entertainment  2011  24600000            gaming  hacked
208     Sony PlayStation Network  2011  77000000            gaming  hacked

In [19]:
data[data['Organization type'] == 'gaming']['Year'].value_counts()

2011    4
2020    2
2018    1
2012    1
2013    1
2016    1
Name: Year, dtype: int64

In [21]:
data[data['Organization type']=='financial']['Year'].value_counts()

2005    5
2012    4
2008    3
2019    3
2011    3
2007    3
2010    3
2009    2
2006    2
2015    2
2014    2
2020    2
2016    1
2013    1
Name: Year, dtype: int64

In [23]:
data[data['Organization type']=='financial']['Method'].value_counts()

hacked                    17
lost / stolen media        7
inside job                 6
poor security              2
unsecured S3 bucket        1
intentionally lost         1
rogue contractor           1
accidentally published     1
Name: Method, dtype: int64

In [24]:
data[data['Organization type']=='government']['Year'].value_counts()

2008    6
2012    4
2011    4
2007    3
2013    3
2016    2
2010    2
2015    2
2018    1
Name: Year, dtype: int64

In [25]:
data[data['Organization type']=='financial']['Method'].value_counts()

hacked                    17
lost / stolen media        7
inside job                 6
poor security              2
unsecured S3 bucket        1
intentionally lost         1
rogue contractor           1
accidentally published     1
Name: Method, dtype: int64

In [26]:
data[data['Organization type']=='retail']['Year'].value_counts()

2007    4
2015    3
2014    3
2019    2
2011    2
2005    1
2018    1
2008    1
2016    1
2013    1
2020    1
Name: Year, dtype: int64

In [28]:
data[data['Organization type']=='retail']['Method'].value_counts()

hacked                    16
lost / stolen computer     2
inside job                 1
poor security              1
Name: Method, dtype: int64